name       : rpi-imager
version    : 1.7.4.1
release    : 4
source     :
    - https://github.com/raspberrypi/rpi-imager/archive/refs/tags/v1.7.4.1.tar.gz : 5dad541afbdb2193f2b2f2b80695b340c4c8c86bb3cbccce68491f4f3c28f6b8
license    : Apache-2.0
homepage   : https://github.com/raspberrypi/rpi-imager
component  : system.utils
summary    : Raspberry Pi Imager can flash an OS to a sdcard for use in your rpi with options to make the initial configuration easier pre-boot.
description: |
    Raspberry Pi Imager can flash an OS to a sdcard for use in your rpi with options to make the initial configuration easier, such as setting up username, password, hostname, wifi, sshd and locale before the initial boot.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(libarchive)
    - pkgconfig(libcurl)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
rundeps    :
    - qt5-quickcontrols2
setup      : |
    %cmake_ninja -S src -DENABLE_CHECK_VERSION=OFF -DENABLE_TELEMETRY=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
