name       : rpi-imager
version    : 1.7.4
release    : 3
source     :
    - https://github.com/raspberrypi/rpi-imager/archive/refs/tags/v1.7.4.tar.gz : c605a4770da5dbae67fa775bad226311529450fd6ef1fdec708f9f384d1aff34
license    : Apache-2.0
homepage   : https://github.com/raspberrypi/rpi-imager
component  : system.utils
summary    : Raspberry Pi Imager can flash an OS to a sdcard for use in your rpi with options to make the initial configuration easier pre-boot.
description: |
    Raspberry Pi Imager can flash an OS to a sdcard for use in your rpi with options to make the initial configuration easier, such as setting up username, password, hostname, wifi, sshd and locale before the initial boot.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(libarchive)
    - pkgconfig(libcurl)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
rundeps    :
    - qt5-quickcontrols2
setup      : |
    %cmake_ninja -S src -DENABLE_CHECK_VERSION=OFF -DENABLE_TELEMETRY=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
