name       : rpi-imager
version    : 1.7.2
release    : 1
source     :
    - https://github.com/raspberrypi/rpi-imager/archive/refs/tags/v1.7.2.tar.gz : babdcda0a38c5dc3893eef3d2d7138d6d23ba7e306f0f840b6970c579490a57a
license    : Apache-2.0
component  : system.utils
summary    : Raspberry Pi Imager can flash an OS to a sdcard for use in your rpi with options to make the initial configuration easier pre-boot.
description: |
     Raspberry Pi Imager can flash an OS to a sdcard for use in your rpi with options to make the initial configuration easier, such as setting up username, password, hostname, wifi, sshd and locale before the initial boot.
builddeps  :
    - pkgconfig(libarchive)
    - pkgconfig(libcurl)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
rundeps    :
    - qt5-quickcontrols2
setup      : |
    %cmake_ninja -S src -DENABLE_CHECK_VERSION=OFF -DENABLE_TELEMETRY=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
